force-app/main/default/objects/DomainMapping__mdt/DomainMapping__mdt.object-meta.xml
<CustomObject>
    <label>Domain Mapping</label>
    <pluralLabel>Domain Mappings</pluralLabel>
</CustomObject>

force-app/main/default/objects/DomainMapping__mdt/fields/DomainClass__c.field-meta.xml
<CustomField>
    <fullName>DomainClass__c</fullName>
    <label>Domain Class</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Account</fullName>
                <default>true</default>
                <label>Account</label>
            </value>
            <value>
                <fullName>Contact</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DomainMapping__mdt/fields/RepositoryClass__c.field-meta.xml
<CustomField>
    <fullName>RepositoryClass__c</fullName>
    <label>Repository Class</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>AccountRepositoryImpl</fullName>
                <default>true</default>
                <label>AccountRepositoryImpl</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DomainMapping__mdt/fields/ServiceClass__c.field-meta.xml
<CustomField>
    <fullName>ServiceClass__c</fullName>
    <label>Service Class</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>AccountService</fullName>
            </value>
            <value>
                <fullName>ContactService</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/shared/main/infrastructure/mapper/Mapper.cls
public class Mapper {
    private final static String SUFFIX = 'Mapper';

    public static List<Object> mapToDomain(List<SObject> records) {
        String sObjectName = records[0].getSObjectType().getDescribe().getName();
        return getDomainMapper(sObjectName).mapToDomain(records);
    }

    public static List<SObject> mapToEntity(List<Object> domainRecords, List<SObject> records) {
        String sObjectName = records[0].getSObjectType().getDescribe().getName();
        return getDomainMapper(sObjectName).mapToEntity(domainRecords, records);
    }

    public static List<SObject> mapToEntity(List<Object> domainRecords, String objectName) {
        return getDomainMapper(objectName).mapToEntity(domainRecords);
    }

    public static TriggerService getTriggerService(String objectName) {
        DomainMapping__mdt domainMapping = DomainMapping__mdt.getInstance(objectName);
        TriggerService triggerService = (TriggerService) Type.forName(domainMapping.ServiceClass__c)
            .newInstance();
        return triggerService.init(Type.forName(domainMapping.RepositoryClass__c));
    }

    private static DomainMapper getDomainMapper(String objectName) {
        return (DomainMapper) Type.forName(
                DomainMapping__mdt.getInstance(objectName).DomainClass__c + SUFFIX
            )
            .newInstance();
    }
}